### ISSUE TITLE
Separate linting in separate steps

### ISSUE THREAD

**Issue by fedem-p** [fedem-p/BudgetApp2.0#1]
Adjust pipelines in:  `BudgetApp2.0/.github/workflows/check_and_test.yml`

# Current behavior
Currently the linting is all performed in one step by running black, isort and pylint one after the other.

# Problem setting
This means that if any one of these checks fails then the whole pipeline fails.

Each linting command should be separated in their own steps and made dependent on the previous:

# Hint / How to do it
To separate:

create a separate `step` for each linting command.

to make them dependent:
add the line: `needs: <name of the step>

And use the following order

black
isort (needs black)
pylint (needs isort)

**Comment by aishwarya0109** [comment]
Done
